//! `demo` —— 录一段被检查项目的 CLI，产出会动的 SVG。
//!
//! 一个 CLI 的 README 里最该有、也最常缺的东西是**一段真的跑起来的录屏**。
//! 「怎么用」写一屏字，不如八秒的动画。
//!
//! **为什么不直接调 [VHS](https://github.com/charmbracelet/vhs)。** VHS 是个好
//! 东西，但它要 ttyd 和 ffmpeg，产出的是 GIF——而 GIF 与这个仓库对自己每一个
//! 产物的三条约束（自包含、确定性、纯文本）全不相容：二进制大块会撑肥 git
//! 历史，没有文本层意味着录屏里那行命令复制不走，而要求使用者先装一条视频
//! 工具链，对一个「让你的仓库体面起来」的工具来说是本末倒置。
//!
//! 所以录制与渲染都在这个仓库里：[`crate::record`] 跑命令并捕获输出，
//! [`repolish_render::cast`] 把它画成一张用 CSS 动画驱动的 SVG。没有外部依赖，
//! 同一次录制逐字节一致，命令行里那行字是**真的文字**。
//!
//! tape 没有删掉：`--tape` 仍然写一份 VHS 脚本，给确实想要 GIF 的人。
//!
//! **挑哪几条命令入镜是作者的判断，不是我们的。** 默认只录 `--help`，
//! 那是对任何 CLI 都成立的唯一一条命令。

use repolish_core::RepoContext;
use repolish_ingest::Profile;

/// 录屏动画在用户仓库中的默认位置
pub const SVG_PATH: &str = ".repolish/demo.svg";
/// VHS tape 的默认位置，`--tape` 才写
pub const TAPE_PATH: &str = ".repolish/demo.tape";
/// VHS 渲染出来的 GIF
pub const GIF_PATH: &str = ".repolish/demo.gif";

/// 这个项目有没有一个可以录的 CLI，有的话叫什么。
///
/// 三处依次问：包清单声明的可执行文件、profile 探测的结论、包名本身。
/// 一个都答不上来就返回 `None`——录一段跑不起来的命令，比没有录屏更糟。
pub fn binary(ctx: &RepoContext) -> Option<String> {
    if let Some(bin) = ctx.manifests.iter().find_map(|m| m.bins.first()) {
        return Some(bin.clone());
    }
    if ctx.profile != Profile::Cli {
        return None;
    }
    // profile 判成 CLI 但清单里没声明 bin：包名通常就是命令名
    // （Go、Python 的入口脚本都不在我们解析的字段里）
    ctx.package_name()
        .map(repolish_ingest::normalize_package_name)
        .or_else(|| Some(ctx.display_name()))
        .filter(|n| !n.is_empty())
}

/// 默认录哪几条命令。
///
/// `--help` 是唯一一条**对任何 CLI 都成立**的命令，所以它是默认值的全部。
/// 再多猜一条子命令，就有一半的概率录出一屏 "unknown subcommand"。
/// 想录别的，`--cmd` 给。
pub fn default_commands(bin: &str) -> Vec<String> {
    vec![format!("{bin} --help")]
}

/// 生成 tape。
///
/// 配色与 repolish 自己的演示同源（见 `repolish-render/src/theme.rs`），
/// 但这是**用户仓库里的文件**，改成什么样是他的自由——所以主题整段写死在
/// tape 里，而不是引一个我们的配置文件。
pub fn tape(bin: &str, commands: &[String], gif_path: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# A terminal recording of {bin}, rendered with VHS.\n\
         #\n\
         #   vhs {TAPE_PATH}\n\
         #\n\
         # VHS needs ttyd and ffmpeg. If you cannot install them locally, render this on a\n\
         # Linux runner in CI: https://github.com/charmbracelet/vhs-action\n\
         #\n\
         # Generated by `repolish --stages demo`. Edit it freely — it is your file now. The commands\n\
         # below are the ones worth showing a first-time reader; add, cut and reorder them.\n\
         #\n\
         # `{bin}` has to be on PATH when this runs. In CI, build it first and prepend the\n\
         # build directory to $GITHUB_PATH, or the recording will be a shell error.\n\n"
    ));

    out.push_str(&format!("Output {gif_path}\n\n"));
    out.push_str(
        "Set Shell bash\n\
         Set FontSize 15\n\
         Set Width 1180\n\
         Set Height 700\n\
         Set Padding 26\n\
         Set TypingSpeed 45ms\n\n",
    );
    out.push_str(&format!("Set Theme {}\n\n", THEME));

    out.push_str(
        "# The prompt and any warm-up go here, off camera: the viewer came to see the\n\
         # tool, not how the stage was set.\n\
         Hide\n\
         Type \"clear\" Enter\n\
         Sleep 500ms\n\
         Show\n\n",
    );

    for (i, cmd) in commands.iter().enumerate() {
        if i > 0 {
            out.push_str("Type \"clear\" Enter\nSleep 300ms\n\n");
        }
        out.push_str(&format!(
            "Type \"{}\" Sleep 700ms Enter\nSleep 5s\n\n",
            cmd.replace('\\', "\\\\").replace('"', "\\\"")
        ));
    }
    out.push_str("Sleep 2s\n");
    out
}

/// tape 里的配色。与 `repolish-render/src/theme.rs` 的 `DARK` 同源。
const THEME: &str = r##"{ "background": "#1a1a24", "foreground": "#edebfa", "cursor": "#ff5fd1", "selection": "#35334a", "black": "#1a1a24", "red": "#ff4f6e", "green": "#a9f05f", "yellow": "#ffc53d", "blue": "#7d56f4", "magenta": "#ff5fd1", "cyan": "#43e5d0", "white": "#edebfa", "brightBlack": "#8b87a3", "brightRed": "#ff4f6e", "brightGreen": "#a9f05f", "brightYellow": "#ffc53d", "brightBlue": "#7d56f4", "brightMagenta": "#ff5fd1", "brightCyan": "#43e5d0", "brightWhite": "#ffffff" }"##;

/// 一段可以贴进 README 的引用
pub fn snippet(path: &str, alt: &str) -> String {
    format!("![{alt}]({path})")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tape_declares_its_output_and_the_commands_to_record() {
        let t = tape("taskvault", &default_commands("taskvault"), GIF_PATH);
        assert!(t.contains("Output .repolish/demo.gif"));
        assert!(t.contains(r#"Type "taskvault --help""#));
        assert!(t.starts_with('#'), "开头该是说明，说清这份文件是什么");
    }

    /// tape 是一门有引号的小语言，命令里的引号不转义会把脚本弄坏
    #[test]
    fn quotes_inside_a_command_are_escaped() {
        let t = tape("t", &[r#"t check --only "a,b""#.to_string()], GIF_PATH);
        assert!(t.contains(r#"Type "t check --only \"a,b\"""#), "{t}");
    }

    #[test]
    fn several_commands_are_separated_by_a_clear() {
        let t = tape("t", &["t a".into(), "t b".into()], GIF_PATH);
        assert_eq!(t.matches(r#"Type "clear" Enter"#).count(), 2);
        assert!(t.find("t a").unwrap() < t.find("t b").unwrap());
    }

    /// `--help` 是唯一一条对任何 CLI 都成立的命令
    #[test]
    fn the_default_recording_is_just_the_help_output() {
        assert_eq!(default_commands("rg"), vec!["rg --help"]);
    }

    #[test]
    fn the_svg_and_the_tape_do_not_share_a_path() {
        // 一个是我们自己渲染的动画，一个是给 vhs 用的脚本。
        // 撞在一起的话，--tape 会把动画覆盖掉。
        assert_ne!(SVG_PATH, TAPE_PATH);
        assert!(SVG_PATH.ends_with(".svg"));
    }

    #[test]
    fn the_theme_matches_the_brand_palette() {
        assert!(THEME.contains(&repolish_render::DARK.bg.to_string()));
        assert!(THEME.contains(&repolish_render::theme::PINK.to_string()));
    }
}
